"""empty message

Revision ID: b656ea76bf4c
Revises: 5b1f2fc558b1
Create Date: 2024-01-29 13:35:42.204145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b656ea76bf4c'
down_revision = '5b1f2fc558b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prediction_request', schema=None) as batch_op:
        batch_op.create_unique_constraint('_username_country_city_uc', ['username', 'country_code', 'city'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prediction_request', schema=None) as batch_op:
        batch_op.drop_constraint('_username_country_city_uc', type_='unique')

    # ### end Alembic commands ###
